version: '1'
services:
  oven:
    image: oven
    container_name: oven
    hostname: oven
    volumes:
      - ./oven:/code
    ports:
      - "8000:8000"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: unless-stopped
    container_name: zookeeper
    volumes:
      - ./zookeeper:/home
  broker:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    container_name: broker
    links:
      - zookeeper
    volumes:
      - ./broker/:/home
  kafkaproducer:
    image: kafkaproducer
    container_name: kafkaproducer
    hostname: kafkaproducer
    links:
      - broker
    depends_on:
      - broker
      - oven
    user: root
    environment:
      KAFKA_BROKER: broker:9092 
    volumes:
      - ./kafkaproducer/:/home
  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: spark
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home
